name: EC2 Instance Management

# Trigger the workflow on push to the main branch
on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master
  workflow_dispatch:  # Allow manual trigger via GitHub UI

jobs:
  setup:
    runs-on: ubuntu-latest  # Use an Ubuntu-based runner

    steps:
    # Checkout the repository
    - name: Checkout Repository
      uses: actions/checkout@v2

    # Set up Python
    - name: Set up Python 3.8
      uses: actions/setup-python@v2
      with:
        python-version: '3.8'

    # Install dependencies
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt

    # Run the EC2 Management scripts
    - name: Run EC2 List Instances
      run: |
        python list_vms.py

    - name: Run EC2 Create Instance (optional, can be modified to launch an instance)
      run: |
        python create_vms.py

    - name: Run EC2 Instance Info (Optional)
      run: |
        python get_instance_info.py
