name: EC2 Instance Management

# Trigger the workflow on push to the main branch
on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
  workflow_dispatch:  # Allow manual trigger via GitHub UI

jobs:
  setup:
    runs-on: ubuntu-latest  # Use an Ubuntu-based runner

    steps:
    # Checkout the repository
    - name: Checkout Repository
      uses: actions/checkout@v2

    # Set up Python
    - name: Set up Python 3.8
      uses: actions/setup-python@v2
      with:
        python-version: '3.8'

    # Install dependencies
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt

    # Run the EC2 List Instances
    - name: Run EC2 List Instances
      env:
        AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
        AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        AWS_REGION: ${{ secrets.AWS_REGION }}
      run: |
        python list_vms.py || echo "AWS Credentials not available or invalid. Skipping EC2 list step."

    # Run EC2 Create Instance (optional, can be modified to launch an instance)
    - name: Run EC2 Create Instance (Optional)
      env:
        AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
        AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        AWS_REGION: ${{ secrets.AWS_REGION }}
      run: |
        python create_vms.py || echo "AWS Credentials not available or invalid. Skipping EC2 create step."

    # Run EC2 Instance Info (Optional)
    - name: Run EC2 Instance Info (Optional)
      env:
        AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
        AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        AWS_REGION: ${{ secrets.AWS_REGION }}
      run: |
        python get_instance_info.py || echo "AWS Credentials not available or invalid. Skipping EC2 info step."
